version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: news-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: news-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: news-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: news_db
            MYSQL_USER: news_user
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    queue:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: news-queue
        command: php artisan queue:work
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        networks:
            - laravel

    scheduler:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: news-scheduler
        entrypoint: ["sh", "./docker/scheduler/schedule-cron.sh"]
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
        driver: bridge
